repo_url: https://github.com/vitorfleonardo/VerificAAA
repo_name: VerificAAA

site_url: https://github.com/vitorfleonardo/VerificAAA
site_name: VerificAAA

use_directory_urls: False

nav:
  - Início - VerificAAA: 'index.md'

  - Desenvolvimento Web:
    - Desenvolvimento: 'devWeb/non_text_content.md'

  - Design:
    - Design: 'design/design.md'
  
  - Geração de Conteúdo:
    - Conteúdo: 'geracaoConteudo/conteudo.md'

  - Gestão de Projetos:
    - Gestão de Projetos: 'gestaoProjeto/gestaoProjeto.md'

  - Ferramentas:
    - Ferramentas de Acessibilidade: 'tools/ferramentas.md'

  - TG-02:
    - Site Avaliado: 'tg-02/siteAvaliado/siteAvaliado.md'
    - Avaliação Web: 'tg-02/avaliaWeb/avaliaWeb.md'
    - Avaliação Design: 'tg-02/avaliaDesign/index.md'
    - Avaliação Geração: 'tg-02/avaliaGer/index.md'
    - Avaliação Gestão: 'tg-02/avaliaGes/index.md'

  - TG-03: 'tg-03/saasable-ui-main/'

theme:
  name: readthedocs
  locale: pt_BR
  titles_only: true
  logo: imagens/logo-verificaaa.png
  favicon: imagens/logo-verificaaa.png

plugins:
  - search:
      lang: pt

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true  
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vitorfleonardo/VerificAAA
      name: Repositório no GitHub
  
  version:
    provider: mike

copyright: Copyright &copy; 2025 - Equipe VerificAAA