repo_url: https://github.com/UnBIHC2025-1/ihc2025.1-grupo1
repo_name: ihc2025.1-grupo1

site_url: https://unbihc2025-1.github.io/ihc2025.1-grupo1/
site_name: WebAAA

use_directory_urls: True

nav:
  - Início: 'index.md'
  - Desenvolvimento Web: 'devWeb/non_text_content.md'
  - Design: 'design/design.md'
  - Geração de Conteúdo: 'geracaoConteudo/conteudo.md'
  - Gestão de Projetos: 'gestaoProjeto/gestaoProjeto.md'
  - Ferramentas: 'tools/ferramentas.md'
  - Site Avaliado: 'siteAvaliado/siteAvaliado.md'
  - Avaliação de desenvolvimento web: 'avaliaWeb/avaliaWeb.md'
  - Avaliação de design: 'avaliaDesing/index.md'
  - Avaliação de geração de conteúdo: 'avaliaGer/index.md'
  - Avaliação de gestão de projeto: 'avaliaGes/index.md'
  - Avaliação de ferramentas: 'avaliaFer/index.md'

theme:
  name: material
  language: pt
  logo: imagens/logo-verificaaa.png
  favicon: imagens/logo-verificaaa.png

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: true

extra_css:
  - stylesheets/extra.css
